### PR TITLE
fix(ui): add followee button visibility after addition

### LINKED ISSUE #6715: Fix: “Add Followee” Button becomes partially hidden after adding first followee
### Fix “Add Followee” Button Becomes Partially Hidden After Adding First Followee
URL: https://nns.ic0.app/

**Issue Summary**
After adding the first followee in the “Follow neurons” modal, the “Add Followee” button becomes partially hidden, making it difficult or impossible to add additional followees.

**Steps to Reproduce:**
1. Go to https://nns.ic0.app/
2. Navigate to Neuron Staking
3. Select a Staked Neuron
4. Click “Follow neurons”
5. Open any Topic
6. Click “Add Followee”
7. Add a first followee by clicking “Follow”
8. Notice that the “Add Followee” button becomes partially hidden, preventing easy addition of a second followee.

**Expected Behavior**
The “Add Followee” button should remain fully visible and accessible at all times, regardless of how many followees have been added.

**Environment:**

OS: macOS Sequoia
Browser: Chrome Version 135.0.7049.85 (Official Build) (arm64)
Screen Resolution: Irrelevant (issue persists across resolutions)

https://github.com/user-attachments/assets/bc50ee2b-80ab-479c-8874-34dbe2c70f3b

### PR DESCRIPTION
**Pull request by yhabib**
# Motivation

We have an issue with the "Add Followee" button, which becomes partially hidden after adding a followee (#6715).

This problem relates to how Svelte calculates dynamic spaces for our `Collapsible` component.  As this flow will be change in a near future to to use topic following similar to how the SNS governance is handled, the propose solution is to force `Collapsible` to re-calculate its height by updating one prop.

Before:

https://github.com/user-attachments/assets/e7a5d55c-56d6-41de-981c-e9a54d0c67ce

After:

https://github.com/user-attachments/assets/1d12ed49-3f3a-4494-ae45-925ab5f59d69

Closes #6715.

# Changes

- Temporarily change a prop to retrigger the height calculation.
- Refactor to Svelte 5.

# Tests

- Update unit tests
- Tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network)

# Todos

- [ ] Add entry to changelog (if necessary).

### CODE REVIEW

File: frontend/src/lib/components/neurons/FollowTopicSection.svelte [hunk 1]
```diff
@@ -1,26 +1,40 @@
...
+  const { id, count, openNewFolloweeModal }: Props = $props();
+  const defaultTestId = "collapsible";
+  let testId = $state(defaultTestId);
+
+  $effect(() => {
+    if (count === 0) return;
+    testId = "";
+
+    setTimeout(() => {
+      testId = defaultTestId;
```
Comment (mstrasinskis) [inline frontend/src/lib/components/neurons/FollowTopicSection.svelte:20]: Does this trigger update of the Collapsible?

**Review by mstrasinskis — APPROVED** [review]
Thanks!

File: frontend/src/lib/components/neurons/FollowTopicSection.svelte (hunk 1 above)
Comment (yhabib) [reply frontend/src/lib/components/neurons/FollowTopicSection.svelte:20]: Only the collapsible contents are affected; it does not close or open them but rather re-renders the children.
